#!/bin/sh
if [ -z "$1" ]; then exit 1; fi;

SLN_PATH=$(winepath -u "$2")
FILE_PATH_AND_LINE=$(winepath -u "$3")

SLN_DIR=$(dirname "$SLN_PATH")

SLN_NAME="${SLN_PATH#$SLN_DIR}"
SLN_NAME="${SLN_NAME#?}"					#remove '/'
SLN_NAME="${SLN_NAME/.sln/-csharp.sln}"		#open -csharp.sln

LOCAL_TO_SLN_FILE_PATH_AND_LINE="${FILE_PATH_AND_LINE#$SLN_DIR}"
LOCAL_TO_SLN_FILE_PATH_AND_LINE="${LOCAL_TO_SLN_FILE_PATH_AND_LINE#?}"
FILE_LINE="${LOCAL_TO_SLN_FILE_PATH_AND_LINE##*;}"
LOCAL_TO_SLN_FILE_PATH="${LOCAL_TO_SLN_FILE_PATH_AND_LINE%;$FILE_LINE}"
LOCAL_TO_SLN_FILE_DIR=$(dirname "$LOCAL_TO_SLN_FILE_PATH")
FILE_NAME="${LOCAL_TO_SLN_FILE_PATH#$LOCAL_TO_SLN_FILE_DIR}"
FILE_NAME="${FILE_NAME#?}"

if [ $FILE_LINE == "-1" ]; then FILE_LINE="0"; fi;

#to go back ../ for number of folders in which file is -1
COUNT="${LOCAL_TO_SLN_FILE_PATH//[^\/]}"
COUNT="${#COUNT}"
COUNT="$((COUNT - 1))"

BACKWARD_SLN_DIR = ""
for i in $(seq 0 $COUNT); do BACKWARD_SLN_DIR="${BACKWARD_SLN_DIR}../"; done

#Unity calls monodevelop from project directory which is SLN_DIR
ln -s "/" "${SLN_DIR}/Z:"
cd "${SLN_DIR}/$LOCAL_TO_SLN_FILE_DIR"

PREV_SLN_NAME=$(head -n 1 "${SLN_DIR}/sln_name_of_last_monodevelop_call")

if [ "$(pidof monodevelop)" ] && [ $PREV_SLN_NAME == $SLN_NAME ]
then /bin/monodevelop "$FILE_NAME;$FILE_LINE"
else /bin/monodevelop "${BACKWARD_SLN_DIR}/$SLN_NAME $FILE_NAME;$FILE_LINE"
fi

echo "$SLN_NAME" > "${SLN_DIR}/sln_name_of_last_monodevelop_call"

exit 0
